### ISSUE TITLE
Geofs SkyX is not working on chrome

### ISSUE THREAD

**Issue by kan78089** [geofs-plugins/plugin-manager#12]
![image](https://user-images.githubusercontent.com/70948456/92470238-ca346600-f1f3-11ea-8a46-d229a6abc48e.png)

**Comment by kan78089** [comment]
it's not working on chrome

please help us

**Comment by yotam180** [comment]
I believe @ron-popov is willing to assist with this one

**Comment by kan78089** [comment]
![image](https://user-images.githubusercontent.com/70948456/101612604-d4534400-3a30-11eb-9d55-02bb845d1da7.png)

hi,

if i click b-2a plane and it will lag again please help us to fix this

**Comment by kan78089** [comment]
and it will glitch

**Comment by yotam180** [comment]
How did you even get the extension? It was down for, like, 2 years now

**Comment by kan78089** [comment]
which extension?

**Comment by kan78089** [comment]
fmc?

**Comment by yotam180** [comment]
If you're talking about FMC, we're not the authors and you're in the wrong place 😅

**Comment by kan78089** [comment]
hahaha

**Comment by latam5** [comment]
I got it by downloading the files on github, then remaking a extension file
then i just had to put it on ( the planes of skyx do not  load for some
reason=)

Le mer. 9 déc. 2020 à 17:17, Yotam Salmon <notifications@github.com> a
écrit :

**Comment by latam5** [comment]
ui had all the extension settings like voice chat but when i go to aircraft
and click on one of the aircraft it will not load and crashes the game,
I was wondering if it was because there was not the aircraft hangar or
something like that that was missing
cheers
Latam

**Comment by ron-popov** [comment]
SKYX is not supported anymore.

**Comment by latam5** [comment]
Hello  kan78089,
To make it work, got to options and try putting the rendering option to
lower settings
happy flying
Latam
