### ISSUE TITLE
Autopilot++ Occasionally Disengages on its own

### ISSUE THREAD

**Issue by shantanubdas2002** [geofs-plugins/plugin-manager#4]
First of all, I love Autopilot++ so much and I feel its very useful. But there is a small bug I face with Autopilot++ where it disengages on its own. Sometimes while I'm flying my AP++ disengages on its own causing my plane in the game to descend very slowly and hit the ground.

I also face this problem when I refresh my page and I insert my AP settings again. Sometimes when my plane crashes, I refresh my page while in the air and I have to reinsert all my AP settings and engage it. However it  disengages, which causes my plane to be manually controllable even though engaged and also causes my plane to crash. Any advice?

QANTAS PLEASE FIX IT!

**Comment by ron-popov** [comment]
We are the devs of SkyX and not autopilot++ , please contact the devs of autopilot++ regarding this issue.

**Comment by yotam180** [comment]
We are not linked to the development of AP++. Please see Karl Cheng's Autopilot++ issues thread: https://github.com/Qantas94Heavy/autopilot-pp/issues

**Comment by shantanubdas2002** [comment]
Oops I apologize. I was supposed to post there but posted here by accident. Forgive me boi.. LOL
