### ISSUE TITLE
Plugins seem to load twice

### ISSUE THREAD

**Issue by yotam180** [geofs-plugins/plugin-manager#6]
**Hey Ron**, 
Here's another issue for you to fill your weekend :)

After splitting the plugins at the server, the extension seems to load everything twice.

(Look at the screenshot)

![default](https://user-images.githubusercontent.com/10270110/27490244-2f1d25f2-5846-11e7-81cc-6c53806117b9.JPG)

It might be my fault (I might have done something wrong at the server). Can you check it to make sure the plugin loader is not loading anything twice?

Thanks.

**Comment by ron-popov** [comment]
It seems like both the Automatic ATC plugin and aircraft warehouse plugin are adding the ATC button , i'm closing this since this is related to the plugins and not the plugin manager.

**Comment by yotam180** [comment]
No, when requesting _'load.php'_ from the server with _ids=aircraft_warehouse_, it returns a Javascript code that does not load the ATC button..

I think it's a problem with the manager, its auto-update might be faulty.

**Comment by ron-popov** [comment]
Did you change the last_modified variable ?

**Comment by yotam180** [comment]
Ok, the last_modified variable is now working well. Seems like PHP's *touch()* didn't do what I expected it to do. OoPs :joy:

I committed a new version for the extension, seems to be working now.

Closed.
