### ISSUE TITLE
Plugins menu overflows onto the developer mode menu

### ISSUE THREAD

**Issue by ron-popov** [geofs-plugins/plugin-manager#7]
When toggling the developer mode menu , the plugins menu overflows right into the developer menu and then you can see only 3 plugins.

![image](https://user-images.githubusercontent.com/21021989/27510583-beeb8760-591c-11e7-8bb6-e46a5c11f7db.png)

Some html magic is required in order to fix this

**Comment by yotam180** [comment]
Why am I assigned to this? :joy:

**Comment by ron-popov** [comment]
Cus it's UI and UI is not my thing.

**Comment by yotam180** [comment]
I hate UIs :cry:

Ok, I'll figure it out on Tuesday. Go to sleep, we've got a competition to win tomorrow :grinning:

**Comment by yotam180** [comment]
Fixed?

**Comment by ron-popov** [comment]
Nope

**Comment by yotam180** [comment]
But no one cares.

**Comment by ron-popov** [comment]
If it doesn't work it's an issue.

**Comment by yotam180** [comment]
"If a tree falls down but no-one cares, the tree didn't fell down"
 -Descartes. (Or something like that)

No one cares about this issue, so it basically doesn't exist.
Proven.
1=2.
Bye

**Comment by ron-popov** [comment]
It doesn't work ffs

**Comment by yotam180** [comment]
I doesn't care ffs

**Comment by ron-popov** [comment]
It doesn't work , if you fix it , you close it.

**Comment by yotam180** [comment]
It doesn't work, if you mean to fix it, you keep it.

**Comment by ron-popov** [comment]
I might fix it

**Comment by yotam180** [comment]
So you might reopen it when you're sure about it.

**Comment by ron-popov** [comment]
Someone will fix it in the future

**Comment by yotam180** [comment]
רון
די
לאף אחד לא אכפת

**Comment by ron-popov** [comment]
זה יתוקן בעתיד
יותם
זה לא עובד

**Comment by yotam180** [comment]
![סוכה בלאט רון](https://images-na.ssl-images-amazon.com/images/I/618tGs2yNoL._SX355_.jpg)

Niet.

**Comment by yotam180** [comment]
Will or will not be fixed in 2.0, if you wish it to be - please move the issue to the new repo.

**Comment by Featherway** [comment]
How do i become a developer

**Comment by ron-popov** [comment]
You learn how to write code and after __developing__ some software you become a developer.
