### ISSUE TITLE
Dependency Tree

### ISSUE THREAD

**Issue by ron-popov** [geofs-plugins/plugin-manager#9]
A system that allows developer to write api's themeselves , the api will load prior to all of the plugins , and the plugins will be able to use the api the other developer wrote

**Comment by yotam180** [comment]
We might improve that even further,

A plugin will have a dependency list, and the plugin manager will load all the dependencies before it loads the plugin. (Of course, checking that no circular dependencies occur, etc, etc)

It can be set within the meta file for the plugin.

**Comment by yotam180** [comment]
Will or will not be implemented in 2.0, if you wish it to be - please move the issue to the new repo.
